#!/bin/bash
COUNT=$#
test $COUNT -lt 1 && {
    echo "Usage: $0 <markdown files>"
    exit 1
}
MKD=`which multimarkdown`
test -z $MKD && {
    MKD=`which markdown`
}
test -z $MKD && {
    echo "ERROR: Please install 'markdown' or 'multimarkdown'"
    exit 1
}

htmlize() {
FILE=$1
HTMLFILE=`echo $FILE | sed -e's:\..*:.html:g'`
IS_OK=`echo $HTMLFILE | grep html | wc -l`
test $IS_OK -eq 0 && {
    echo "ERROR: $FILE is not an acceptable filename. Needs an extension."
    exit 1
}
echo "Using $MKD on $FILE to create $HTMLFILE"
cat > $HTMLFILE << HEADER
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">

    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/pygment_trac.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print" />

    <title>App::financeta by Vikas N Kumar</title>
  </head>

  <body>

    <header>
      <div class="container">
        <h1>financeta</h1>
        <h2>App::financeta is a GUI to perform Technical Analysis for stocks
        using the <a href="http://pdl.perl.org/">Perl Data Language (PDL)</a></h2>

        <section id="downloads">
          <a href="https://github.com/vikasnkumar/financeta/zipball/master" class="btn">Download as .zip</a>
          <a href="https://github.com/vikasnkumar/financeta/tarball/master" class="btn">Download as .tar.gz</a>
          <a href="https://github.com/vikasnkumar/financeta" class="btn btn-github"><span class="icon"></span>View on GitHub</a>
        </section>
      </div>
    </header>

    <div class="container">
      <section id="main_content">

HEADER
$MKD $FILE >> $HTMLFILE

cat >> $HTMLFILE << FOOTER
      </section>
    </div>
    <hr>
    <footer><div class="container">
    <h3>
<a name="authors-and-contributors" class="anchor" href="#authors-and-contributors"><span class="octicon octicon-link"></span></a>Authors and Contributors</h3>

<p>Vikas N Kumar (<a href="https://github.com/vikasnkumar" class="user-mention">@vikasnkumar</a>) is the author of <strong>App::financeta</strong>. All copyrights belong to the authors.</p>
    <br/><br/><strong>Disclaimer:</strong>&nbsp;<em>The authors are not
    responsible for any losses, profits, emotional trauma, hardship or happiness
    resulting from the use of this application. Use the software at your own risk and
    with your own intelligence. The application comes with no warranty. For more
    details refer the <a href="./license.html">license</a> page.</em>
    <br/><br/><p style="font-size:10px;">
        This page was last updated on __FDATE__.
    </p>
    </div></footer>
    
  </body>
</html>
FOOTER
    DATE=`git log -1 --pretty="format:%ai" $FILE`
    sed -i -e "s/__FDATE__/${DATE}/g" $HTMLFILE
}

for i in $@; do
    htmlize $i
done
